services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=password
    ports:
      - 5437:5432
    volumes:
      - ../data/postgis:/var/lib/postgresql/data